version: '3.8'

services:

  frontend:
    image: vhiltzu/sample-frontend
    build: ./example-frontend
    container_name: frontend
    ports:
    - 5000:5000

  backend:
    image: vhiltzu/sample-backend
    build: ./example-backend
    container_name: backend
    ports:
    - 8080:8080
