# Use the golang image version 1.16-alpine
FROM golang:1.16-alpine

# Publish port 8080
EXPOSE 8080

WORKDIR /app

# Copy the source code
COPY . .

# Build the project and create the appuser
RUN go build && \
  adduser web -D && \
  chown web .
USER web

# Run the application
CMD ["./server"]