# Use the golang image version 1.16-alpine
FROM golang:1.16-alpine

# Publish port 8080
EXPOSE 8080

# Define an environment variable for the cors check
ENV REQUEST_ORIGIN=http://localhost:5000

WORKDIR /usr/src/app

# Copy the source code
COPY . .

# Build the project
RUN go build

# Run the application
CMD ["./server"]