# Use the Java 8
FROM amazoncorretto:8

# Publish port 8080
EXPOSE 8080

WORKDIR /usr/src/app

# Copy the source code
COPY . .

# Build the application
RUN ./mvnw package

# Run the application
CMD ["java","-jar","./target/docker-example-1.1.3.jar"]